# Generated by Django 5.0.7 on 2024-08-01 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.city'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cat03.jpg/481px-Cat03.jpg'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
