# Generated by Django 5.0.7 on 2024-08-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_photo_image_photo_url_alter_photo_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
