# Generated by Django 4.2.1 on 2024-08-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_photo_url_remove_product_cities_photo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.city'),
        ),
    ]
